
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false


server.address=0.0.0.0
server.port=8088
server.forward-headers-strategy=framework

management.endpoints.web.exposure.include=*
management.metrics.distribution.percentiles.http.server.requests=0.5,0.9,0.95,0.99
management.metrics.distribution.sla.http.server.requests=500ms,1s,2s